### ISSUE TITLE
Is this being used in practice?

### ISSUE THREAD

**Issue by dumblob** [minkustree/Taskbox#2]
@minkustree I wonder whether you use this app or rather https://github.com/minkustree/CalendarNotification ?

If you use Taskbox, could you shed some light on why you created it? Thanks a lot!

Btw. could you turn on the "Issues" tab in the https://github.com/minkustree/CalendarNotification repo? I would like to discuss (potential) future maintenance/development.

**Comment by minkustree** [comment]
Hi @dumblob. I no longer use these apps. 

I created taskbox as an experiment to recreate the snoozed task functionality from Google Inbox, as it matched my workflow.  I have since migrated to Microsoft To Do. 

Please feel free to fork the CalendarNotification project and continue the work in whatever way you see fit. I am not looking to maintain it for others, but am happy for folks to fork and do their own thing with the code. As such, I hope you understand why  the Issues tab will be left off in that repo.

**Comment by dumblob** [comment]
Yes, thanks for clarification!

>As such, I hope you understand why the Issues tab will be left off in that repo.

At first it seemed to be an oversight as the repo is not archived. Feel free to archive it to make the intentions clear :wink:.

Happy New Year!
